# Generated by Django 4.2.7 on 2023-11-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
